### ISSUE TITLE
Css styles file reference is not correct

### ISSUE THREAD

**Issue by Mikadifo** [BizTheHabesha/local-calendar#6]
Hi! I cloned your project I i got an error saying that the file styles.css was not found, i checked the code and i think you should try using this path instead `='./assets/css/style.css'`.

**Comment by BizTheHabesha** [comment]
> Hi! I cloned your project I i got an error saying that the file styles.css was not found, i checked the code and i think you should try using this path instead `='./assets/css/style.css'`.

Cheers for the suggestion, I merged without even realizing you'd commented!
